name: dask-distributed
prefix: /home/conda/conda/envs/dask-distributed
channels:
- conda-forge
- default
dependencies:
- altair
- bcolz
- blas
- bleach
- blosc
- bokeh
- boost
- boto3
- botocore
- ca-certificates
- cairo
- certifi
- chest
- click
- cloudpickle
- configurable-http-proxy
- coverage
- curl
- cython
- cytoolz
- dask
- decorator
- dill
- distributed
- docutils
- entrypoints
- execnet
- expat
- fastparquet
- feather-format
- flake8
- fontconfig
- freetype
- gettext
- glib
- gmp
- graphviz
- h5py
- harfbuzz
- hdf4
- hdf5
- hdfs3
- heapdict
- html5lib
- icu
- ipykernel
- ipyleaflet
- ipython
- ipython_genutils
- ipywidgets
- jinja2
- jmespath
- joblib
- jpeg
- jsonschema
- jupyter
- jupyter_client
- jupyter_console
- jupyter_core
- jupyterhub
- jupyterlab
- keras
- krb5
- libffi
- libgcc
- libgfortran
- libgsasl
- libhdfs3
- libiconv
- libnetcdf
- libntlm
- libpng
- libsodium
- libtiff
- libtool
- libuuid
- libxml2
- llvmlite
- locket
- markupsafe
- mccabe
- mistune
- mock
- msgpack-python
- nbconvert
- nbformat
- ncurses
- netcdf4
- nodejs
- notebook
- numba
- numexpr
- numpy
- openblas
- openssl
- pamela
- pandas
- pandoc
- pandocfilters
- pango
- partd
- pbr
- pcre
- pexpect
- pickleshare
- pip
- pixman
- ply
- prompt_toolkit
- protobuf
- psutil
- ptyprocess
- py
- pycodestyle
- pyflakes
- pygments
- pyqt
- pytables
- pytest
- pytest-timeout
- pytest-xdist
- python=3.5
- python-dateutil
- python-graphviz
- pytz
- pyyaml
- pyzmq
- qt
- qtconsole
- readline
- requests
- s3fs
- s3transfer
- scikit-learn
- scipy
- setuptools
- simplegeneric
- sip
- six
- snappy
- sortedcontainers
- sqlalchemy
- sqlite
- tblib
- tensorflow
- terminado
- testpath
- theano
- thriftpy
- tk
- toolz
- tornado
- traitlets
- vega
- wcwidth
- webencodings
- wheel
- widgetsnbextension
- xz
- yaml
- zeromq
- zict
- zlib
